@ECHO OFF 
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shader.vert 		        -o spv/vert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shader.frag 		        -o spv/frag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe pbr.vert 		            -o spv/pbrvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe pbr.frag 		            -o spv/pbrfrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe depth.vert			        -o spv/depthvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shaderwire.vert 		    -o spv/vertwire.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shaderwire.frag 		    -o spv/fragwire.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe vertex_instance.vert	    -o spv/vertinstance.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe fragment_instance.frag     -o spv/fraginstance.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe vertex_normal2.vert 	    -o spv/vertnormal.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe geometry_normal2.geom 	    -o spv/geomnormal.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe fragment_normal2.frag 	    -o spv/fragnormal.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shaderempty.frag 		    -o spv/fragempty.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shaderquad.vert 		    -o spv/vertquad.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shaderquad.frag 		    -o spv/fragquad.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe descriptors.vert		    -o spv/descvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe descriptors.frag 		    -o spv/descfrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe gui.vert			        -o spv/guivert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe gui.frag 			        -o spv/guifrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe depth_presspass.frag 	    -o spv/depth_presspass.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe DepthReduction.comp	    -o spv/depthreduction.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe DepthReductionmulti.comp	-o spv/depthreductionmulti.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shadow.frag	            -o spv/shadowfrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shadow.vert	            -o spv/shadowvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shadowpoint.frag	        -o spv/shadowpointfrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe shadowpoint.vert	        -o spv/shadowpointvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe bv.frag					-o spv/bvfrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe bv.vert				    -o spv/bvvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe VisibleClusters.comp		-o spv/visibleclusters.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe CullClusters.comp			-o spv/cullclusters.spv

C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/greyscale.comp		-o spv/compgreyscale.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/shader.comp		-o spv/comp.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/gamma.comp			-o spv/compgamma.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/invert.comp		-o spv/compinvert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/solarize.comp		-o spv/compsolarize.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/edge.comp			-o spv/compedge.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/gaussblur.comp		-o spv/compgaussblur.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Compute/sharpen.comp		-o spv/compsharpen.spv

C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/atmosphere.vert		-o spv/atmospherevert.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/atmosphere.frag		-o spv/atmospherefrag.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/singlescatter.comp		-o spv/singlescatter.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/multiscatter.comp		-o spv/multiscatter.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/multiscattercombine.comp       -o spv/multiscattercombine.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/atmosphereraymarch.frag        -o spv/atmosphereraymarch.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/ambientatmosphere.comp         -o spv/ambientatmosphere.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/clouds_raymarch.vert		-o spv/clouds_raymarchv.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/clouds_raymarch.frag		-o spv/clouds_raymarchf.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/NoiseFill.comp		        -o spv/NoiseFill.spv
C:\VulkanSDK\1.2.148.1\Bin\glslc.exe Sky/NoiseFillErosion.comp	        -o spv/NoiseFillErosion.spv